# -*- coding: utf-8 -*-
"""PreProcessingData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cDMNAtvc3TCfEhv8Ju-5p_xngSNuwYQA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame(np.random.rand(50,3), columns=['A','B','C'])
df

plt.style.use('ggplot')
df.plot(kind ="scatter", x="A", y="B", s= df["C"]*200, color="green");

df = pd.DataFrame(np.random.rand(10,3),columns=['A','B','C'])

df

df.plot(kind='area');

url = 'https://raw.githubusercontent.com/pcsanwald/kaggle-titanic/09a787d9ce7305023dd837bfbc48cd2c69557879/train.csv'
df = pd.read_csv(url)
df

df.info()

df.shape

def create_title(name):
  if '.' in name:
    return name.split(',')[1].split('.')[0].strip()
  else:
    return 'unknown'

create_title('Johnston, Miss. Catherine Helen "Carrie"')

create_title('Montvila, Rev. Juozas')

def categorize_title(title):
  if title in ['Mr']:
    return 1
  elif title in ['Master']:
    return 2
  elif title in ['Ms','Mlle','Miss']:
    return 3
  elif title in ['Mrs','Mme']:
    return 4
  else:
    return 5

categorize_title(create_title('Montvila, Rev. Juozas'))

df['title'] = df['name'].apply(create_title).apply(categorize_title)

df

df = df.drop(['ticket','name'],axis=1)
df

cr = pd.crosstab(df['title'],df['survived'])
cr

crPercent = cr.div(cr.sum(1).astype(float),axis=0)
crPercent

crPercent.plot(kind="bar",title="survive rate by title")
plt.xlabel('Title')
plt.ylabel('Survive rate')

edt = pd.get_dummies(df['embarked'])
edt

df['embarked'].value_counts()

